// <auto-generated />
using System;
using FrenchInvoice.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrenchInvoice.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414081152_AddFixedChargesAndSettings")]
    partial class AddFixedChargesAndSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("FrenchInvoice.Core.Models.BankTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Categorise")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RevenueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Solde")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("RevenueId");

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Declaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateLimite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantCA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantCotisations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodeDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodeFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxApplique")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Justificatif")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.FixedCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FixedCharges");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Revenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenceFacture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Revenues");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresseSiege")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BeneficieACRE")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateDebutActivite")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FraisVariables")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("FranchiseTVA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MentionsLegales")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSiret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodiciteDeclaration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlafondCA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrefixeDevis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrefixeFactures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProchainNumeroDevis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProchainNumeroFacture")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TauxLiberatoire")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TvaIntracommunautaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeActivite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("VersementLiberatoire")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdresseSiege = "",
                            BeneficieACRE = false,
                            FraisVariables = 0m,
                            FranchiseTVA = true,
                            MentionsLegales = "Auto-entreprise - TVA non applicable, article 293B du code général des impôts",
                            NomEntreprise = "",
                            NumeroSiret = "",
                            PeriodiciteDeclaration = "Mensuelle",
                            PlafondCA = 77700m,
                            PrefixeDevis = "DEV-2026-",
                            PrefixeFactures = "FAC-2026-",
                            ProchainNumeroDevis = 1,
                            ProchainNumeroFacture = 1,
                            TauxLiberatoire = 2.2m,
                            TauxTVA = 20m,
                            Telephone = "",
                            TvaIntracommunautaire = "",
                            TypeActivite = "BNC",
                            VersementLiberatoire = false
                        });
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.BankTransaction", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId");

                    b.HasOne("FrenchInvoice.Core.Models.Revenue", "Revenue")
                        .WithMany()
                        .HasForeignKey("RevenueId");

                    b.Navigation("Expense");

                    b.Navigation("Revenue");
                });
#pragma warning restore 612, 618
        }
    }
}
