// <auto-generated />
using System;
using FrenchInvoice.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrenchInvoice.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419083700_AddSubscription")]
    partial class AddSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("FrenchInvoice.Core.Models.AccountingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevenueId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tiers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("RevenueId");

                    b.HasIndex("EntityId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("AccountingEntries");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.AccountingPeriodClosing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDepenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRecettes")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("AccountingPeriodClosings");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.BankTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Categorise")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RevenueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Solde")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("ExpenseId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RevenueId");

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Siret")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SiretDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TvaIntracommunautaire")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("SiretDataId");

                    b.HasIndex("EntityId", "Nom");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.CsvMappingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientColumn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreditColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DateColumn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DebitColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FraisColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeaderRow")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibelleColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModePaiementColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MontantColumn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenceColumn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Separator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SoldeColumn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Nom")
                        .IsUnique();

                    b.ToTable("CsvMappingProfiles");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Declaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateDeclaration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLimite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatePaiement")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JustificatifFileName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantCA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantCotisations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodeDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodeFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxApplique")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresseSiege")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BeneficieACRE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Configured")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDebutActivite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FraisVariables")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("FranchiseTVA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("MentionsLegales")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSiret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodiciteDeclaration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlafondCA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrefixeDevis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrefixeFactures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProchainNumeroDevis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProchainNumeroFacture")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SiretDataId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TauxLiberatoire")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TvaIntracommunautaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeActivite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VersementLiberatoire")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiretDataId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Justificatif")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeReglement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.FixedCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("PropertyId");

                    b.ToTable("FixedCharges");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cadre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminPdf")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DebutPeriode")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinPeriode")
                        .HasColumnType("TEXT");

                    b.Property<string>("MentionsLegales")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCommande")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroContrat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RevenueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeFacture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RevenueId");

                    b.HasIndex("EntityId", "Numero")
                        .IsUnique()
                        .HasFilter("Numero != ''");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeProduit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.PayoutRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BankTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Frais")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantBrut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatementDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankTransactionId");

                    b.HasIndex("EntityId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("Platform", "ExternalId")
                        .IsUnique();

                    b.ToTable("PayoutRecords");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Couleur")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Nom")
                        .IsUnique();

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminPdf")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateValidite")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MentionsLegales")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("EntityId", "Numero")
                        .IsUnique()
                        .HasFilter("Numero != ''");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.QuoteLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("QuoteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteLines");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Revenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JustificatifFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceFacture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Revenues");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.SiretData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivitePrincipale")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivitePrincipaleNAF25")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivitePrincipaleNAF25Siege")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivitePrincipaleSiege")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaractereEmployeur")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategorieEntreprise")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedex")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePaysEtranger")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Commune")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComplementAdresse")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreationEntreprise")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreationSiege")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDebutActivite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFermetureEntreprise")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFermetureSiege")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateMiseAJourInsee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateMiseAJourRne")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departement")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirigeantsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistributionSpeciale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enseigne")
                        .HasColumnType("TEXT");

                    b.Property<string>("Epci")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstAssociation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstBio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstEntrepreneurIndividuel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstEss")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstQualiopi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstRge")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstServicePublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstSiege")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstSocieteMission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EtatAdministratif")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifiantAssociation")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndiceRepetition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibelleCedex")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibelleCommune")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibelleCommuneEtranger")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibellePaysEtranger")
                        .HasColumnType("TEXT");

                    b.Property<string>("LibelleVoie")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListeIdccJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("NatureJuridique")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomCommercial")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomRaisonSociale")
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreEtablissements")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreEtablissementsOuverts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroVoie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionActivitePrincipale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Siren")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Siret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatutDiffusion")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrancheEffectifSalarie")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrancheEffectifSalarieSiege")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeVoie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Siren");

                    b.HasIndex("Siret")
                        .IsUnique();

                    b.ToTable("SiretDatas");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CurrentPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedAttemptsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastStancerPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StancerCardToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.AccountingEntry", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId");

                    b.HasOne("FrenchInvoice.Core.Models.Revenue", "Revenue")
                        .WithMany()
                        .HasForeignKey("RevenueId");

                    b.Navigation("Expense");

                    b.Navigation("Revenue");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.BankTransaction", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("ExpenseId");

                    b.HasOne("FrenchInvoice.Core.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.HasOne("FrenchInvoice.Core.Models.Revenue", "Revenue")
                        .WithMany()
                        .HasForeignKey("RevenueId");

                    b.Navigation("Expense");

                    b.Navigation("Property");

                    b.Navigation("Revenue");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Client", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.HasOne("FrenchInvoice.Core.Models.SiretData", "SiretData")
                        .WithMany()
                        .HasForeignKey("SiretDataId");

                    b.Navigation("Property");

                    b.Navigation("SiretData");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Entity", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.SiretData", "SiretData")
                        .WithMany()
                        .HasForeignKey("SiretDataId");

                    b.Navigation("SiretData");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Expense", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.FixedCharge", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Invoice", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrenchInvoice.Core.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.HasOne("FrenchInvoice.Core.Models.Revenue", "Revenue")
                        .WithMany()
                        .HasForeignKey("RevenueId");

                    b.Navigation("Client");

                    b.Navigation("Property");

                    b.Navigation("Revenue");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.InvoiceLine", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Invoice", "Invoice")
                        .WithMany("Lignes")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.PayoutRecord", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.BankTransaction", "BankTransaction")
                        .WithMany()
                        .HasForeignKey("BankTransactionId");

                    b.HasOne("FrenchInvoice.Core.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.Navigation("BankTransaction");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Quote", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrenchInvoice.Core.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.HasOne("FrenchInvoice.Core.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.Navigation("Client");

                    b.Navigation("Invoice");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.QuoteLine", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Quote", "Quote")
                        .WithMany("Lignes")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Revenue", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Subscription", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.User", b =>
                {
                    b.HasOne("FrenchInvoice.Core.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Invoice", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("FrenchInvoice.Core.Models.Quote", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
